version: '3'
services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
    ports:
      - 5000:5000
    command: npm start
    volumes:
      - ./server:/app 
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    